name: "publsih docker image"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASS}}

      - name: Build and Push Docker image
        run: |
          docker build -t anasdev/node-app .
          docker push anasdev/node-app

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
